#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

apt-get -y update
apt-get -y install nginx
apt-get -y upgrade

echo 'Hello World!' > /etc/nginx/html/index.html
service nginx restart
