#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y upgrade

echo 'Hello World!' > /etc/nginx/sites-available/default
sudo service nginx restart
