#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    1) Listens on port 80.
#    2) Returns a page containing "Hello World!" when queried
#    3) At the root with a curl GET request.

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /var/www/html/index.nginx-debian.html
printf %s "server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /etc/nginx/html;
	index       index.html index.htm;
}
" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
