#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# Redirects to another page with  a "301 Moved Permanently”

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /etc/nginx/html;
	index       index.html index.htm;

	location /redirect_me {
		return 301 http://cuberule.com/;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
